energycity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("theplug.urls",namespace="theplug"))
]

theplug/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings



app_name = "theplug"

urlpatterns = [
    path('', views.PostList.as_view(), name="sign_up"),
    path('<slug:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('login', views.login_view, name="login"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('logout', views.logout_view, name="logout"),
    path('create', views.add_post, name="create_post"),
    path('edit', views.edit_post, name="edit_post"),
    path('delete', views.delete_post, name="delete_post"),
    path('view', views.view_post, name="posts"),
    path('created', views.created_success, name="created"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theplug/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=255)
	body = models.TextField()
	image = models.ImageField(upload_to="img", null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)


	class Meta:
		ordering =['-date_added']

theplug/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db.models import Q
from theplug.models import Post
from django.views import generic





class PostList(generic.ListView):
    queryset = Post.objects.all().order_by('-date_added')
    template_name = 'theplug/sign_up.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'theplug/post_detail.html'



# Create your views here.

def sign_up(request):
	if request.method == "POST":
		print("form submitted")
		username = request.POST.get("username")
		password = request.POST.get("password")
		user = User.objects.create_user(username=username, password=password)
		user.save()

	return render(request, 'theplug/sign_up.html', {})


def login_view(request):
	if request.method == "POST":
		username = request.POST.get("username")
		password = request.POST.get("password")
		try:
			user = User.objects.get(Q(username=username) | Q(email=username))
			if user.check_password(password):
				print("Login successful")
				login(request, user)
			else:
				print("Password incorrect")
		except User.DoesNotExist:
			print("User does not exist!")
		if user:
			return render(request, 'theplug/dashboard.html', {'username':request.user})
	return render(request, 'theplug/login.html', {})


def dashboard(request):
	if request.user.is_authenticated:
		return render(request, 'theplug/dashboard.html', {'username':request.user})
	else:
		return render(request, 'theplug/login.html', {})

def add_post(request):
	if request.user is not None:
		if request.method == "POST":
			title = request.POST.get("title", None)
			body = request.POST.get("body", None)
			image = request.POST.get("file", None)
			new_post = Post.objects.create(title=title, body=body, image=image)
			new_post.save()
			posts = Post.objects.all()[:10]
			return render(request, 'theplug/created_success.html', {'posts':posts})
		else:
			return render(request, 'theplug/create_post.html', {})
	else:
		return render(request, 'theplug/login.html', {})

def view_post(request):
	posts = Post.objects.all()[:10]
	return render(request, "theplug/posts.html", {'posts':posts})

def delete_post(request):
	if request.user.is_authenticated:
		if request.method == "POST":
			# handle form submission
			pass
		else:
			return render(request, 'theplug/posts.html', {})
	else:
		return render(request, 'theplug/login.html', {})

def edit_post(request):
	if request.user.is_authenticated:
		if request.method == "POST":
			# handle form submission
			pass
		else:
			return render(request, 'theplug/edit_post.html', {})
	else:
		return render(request, 'theplug/login.html', {})


def created_success(request):
	posts = Post.objects.all()[:10]
	return render(request, "theplug/created_success.html", {'posts':posts})

def logout_view(request):
	logout(request)
	return render(request, "theplug/login.html", {})

theplug/templates/index.html
{% load static %}
<!doctype html>
<html>
<head>
<title>Official Signup Form Flat Responsive widget Template :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Official Signup Form Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- fonts -->
<link href="//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
<!-- /fonts -->
<!-- css -->
<link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all" />
<link href="css/style.css" rel='stylesheet' type='text/css' media="all" />
<!-- /css -->
</head>
<body>
<h1 class="w3ls">Official Signup Form</h1>
<div class="content-w3ls">
	<div class="content-agile1">
		<h2 class="agileits1">Official</h2>
		<p class="agileits2">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	</div>
	<div class="content-agile2">
		<form action="#" method="post">
			<div class="form-control w3layouts"> 
				<input type="text" id="firstname" name="firstname" placeholder="First Name" title="Please enter your First Name" required="">
			</div>

			<div class="form-control w3layouts">	
				<input type="email" id="email" name="email" placeholder="mail@example.com" title="Please enter a valid email" required="">
			</div>

			<div class="form-control agileinfo">	
				<input type="password" class="lock" name="password" placeholder="Password" id="password1" required="">
			</div>	

			<div class="form-control agileinfo">	
				<input type="password" class="lock" name="confirm-password" placeholder="Confirm Password" id="password2" required="">
			</div>			
			
			<input type="submit" class="register" value="Register">
		</form>
		<script type="text/javascript">
			window.onload = function () {
				document.getElementById("password1").onchange = validatePassword;
				document.getElementById("password2").onchange = validatePassword;
			}
			function validatePassword(){
				var pass2=document.getElementById("password2").value;
				var pass1=document.getElementById("password1").value;
				if(pass1!=pass2)
					document.getElementById("password2").setCustomValidity("Passwords Don't Match");
				else
					document.getElementById("password2").setCustomValidity('');	 
					//empty string means no validation error
			}
		</script>
		<p class="wthree w3l">Fast Signup With Your Favourite Social Profile</p>
		<ul class="social-agileinfo wthree2">
			<li><a href="#"><i class="fa fa-facebook"></i></a></li>
			<li><a href="#"><i class="fa fa-youtube"></i></a></li>
			<li><a href="#"><i class="fa fa-twitter"></i></a></li>
			<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
		</ul>
	</div>
	<div class="clear"></div>
</div>
<p class="copyright w3l">© 2017 Official Signup Form. All Rights Reserved | Design by <a href="https://w3layouts.com/" target="_blank">W3layouts</a></p>
</body>
</html>

theplug/templates/theplug/create_post.html
{% load static %}

<!DOCTYPE html>


<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Dashboard</title>
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
</head>
<body>

	<div class="content-w3ls" style="background: grey;">
	<div class="content-agile1">
		
	</div>
	<div class="content-agile2">
		<form action="{% url 'theplug:create_post' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}

			<div class="form-control w3layouts"> 
				<input type="text" id="firstname" name="title" placeholder="Post Title"  title="Please enter your Username" required="">
			</div>

<br><br>
			<div class="form-control agileinfo">	
				<textarea type="text" class="lock" name="body" placeholder="" id="password1" required="" style="margin-left: 80px;
				height: 300px; width: 300px;">Enter your content here
				</textarea>
				<br><br>
				<input type="file" name="file" style="float: right;">
				<br><br>
			</div>	

	
			
			<input type="submit" class="register" value="Create Post">
		</form>
		
	</div>
	<div class="form-control agileinfo" style="margin-top: 20%; color: white; padding-left: 12px;"> 
				<a href="{% url 'theplug:logout' %}">
					<h3 style="font-style: italic;">logout</h3>
				</a>
			</div>
	<!-- <div class="content-agile2" style="background: grey;">

 
			<div class="form-control w3layouts" style="margin-top: 20%;"> 
				<h3 style="font-style: italic;">Create new Post</h3>
			</div>


			<div class="form-control agileinfo" style="margin-top: 20%; margin-bottom: 50px;">	
				
				<ul style="padding-left: 15px; padding-bottom: 15px;">
			<li style="padding-bottom: 20px;">
				<button style="font-size: 18px;">Add New Post </button>
			</li>
			<li>
				<button style="font-size: 18px;">View all Posts </button>
	</ul>
		</div>	
		<div class="form-control agileinfo" style="margin-top: 20%; color: white; padding-left: 12px;"> 
				<a href="{% url 'theplug:logout' %}">
					<h3 style="font-style: italic;">logout</h3>
				</a>
			</div>
	
			
			
	</div> -->
	<div class="clear"></div>
</div>



</body>
</html>

theplug/templates/theplug/created_success.html
{% load static %}

<!DOCTYPE html>


<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Dashboard</title>
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
</head>
<body>

	<div class="content-w3ls" style="background: grey;">
	<div class="content-agile1">
		
	</div>
	<div class="content-agile2" style="color: white;">
		<h3 style="padding-left: 20px;">Post published successfully !!!</h3>
		<br><br>
		<h5 style="padding-left: 20px;">Lists of recently Published Posts</h5>
		<br>
		<ul style="padding-left: 20px; list-style: bullet;">
			{% for post in posts %}
			<li> {{ post.title }}</li>
			{% endfor %}
		</ul>
	</div>
<br><br><br>
	<div class="form-control agileinfo" style="margin-top: 20%; padding-left: 20px; margin-bottom: 50px;">	
				
				<ul style="padding-left: 15px; padding-bottom: 15px;">
			<li style="padding-bottom: 20px;">
				<button style="font-size: 18px;" onclick="location.href='{% url 'theplug:create_post' %}'">Add Another Post </button>
			</li>
			
	</ul>
		</div>	

		<div class="form-control agileinfo" style="margin-top: 20%; color: white; padding-left: 12px;"> 
				<a href="{% url 'theplug:logout' %}">
					<h3 style="font-style: italic;">logout</h3>
				</a>
			</div>
	<!-- <div class="content-agile2" style="background: grey;">

 
			<div class="form-control w3layouts" style="margin-top: 20%;"> 
				<h3 style="font-style: italic;">Create new Post</h3>
			</div>


			<div class="form-control agileinfo" style="margin-top: 20%; margin-bottom: 50px;">	
				
				<ul style="padding-left: 15px; padding-bottom: 15px;">
			<li style="padding-bottom: 20px;">
				<button style="font-size: 18px;">Add New Post </button>
			</li>
			<li>
				<button style="font-size: 18px;">View all Posts </button>
	</ul>
		</div>	
		<div class="form-control agileinfo" style="margin-top: 20%; color: white; padding-left: 12px;"> 
				<a href="{% url 'theplug:logout' %}">
					<h3 style="font-style: italic;">logout</h3>
				</a>
			</div>
	
			
			
	</div> -->
	<div class="clear"></div>
</div>



</body>
</html>

theplug/templates/theplug/dashboard.html
{% load static %}

<!DOCTYPE html>


<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Dashboard</title>
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
</head>
<body>

	<div class="content-w3ls" style="background: grey;">
	<div class="content-agile1">
		
	</div>
	<div class="content-agile2" style="background: grey;">

 
			<div class="form-control w3layouts" style="margin-top: 20%;"> 
				<h3 style="font-style: italic;">Welcome home, {{ username }}</h3>
			</div>


			<div class="form-control agileinfo" style="margin-top: 20%; margin-bottom: 50px;">	
				
				<ul style="padding-left: 15px; padding-bottom: 15px;">
			<li style="padding-bottom: 20px;">
				<button style="font-size: 18px;" onclick="location.href='{% url 'theplug:create_post' %}'">Add New Post </button>
			</li>
			<li>
				<button style="font-size: 18px;" onclick="location.href='{% url 'theplug:posts' %}'">View all Posts </button>
	</ul>
		</div>	
		<div class="form-control agileinfo" style="margin-top: 20%; color: white; padding-left: 12px;"> 
				<a href="{% url 'theplug:logout' %}">
					<h3 style="font-style: italic;">logout</h3>
				</a>
			</div>
		
			
			
	</div>
	<div class="clear"></div>
</div>



</body>
</html>

theplug/templates/theplug/delete_post.html
{% load static %}

<!DOCTYPE html>


<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Dashboard</title>
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
</head>
<body>

	<div class="content-w3ls" style="background: grey;">
	<div class="content-agile1">
		
	</div>
	<div class="content-agile2" style="background: grey;">

 
			<div class="form-control w3layouts" style="margin-top: 20%;"> 
				<h3 style="font-style: italic;">Welcome home, {{ username }}</h3>
			</div>


			<div class="form-control agileinfo" style="margin-top: 20%; margin-bottom: 50px;">	
				
				<ul style="padding-left: 15px; padding-bottom: 15px;">
			<li style="padding-bottom: 20px;">
				<button style="font-size: 18px;">Add New Post </button>
			</li>
			<li>
				<button style="font-size: 18px;">View all Posts </button>
	</ul>
		</div>	
		<div class="form-control agileinfo" style="margin-top: 20%; color: white; padding-left: 12px;"> 
				<a href="{% url 'theplug:logout' %}">
					<h3 style="font-style: italic;">logout</h3>
				</a>
			</div>
	
			
			
	</div>
	<div class="clear"></div>
</div>



</body>
</html>

theplug/templates/theplug/edit_post.html
{% load static %}

<!DOCTYPE html>


<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Dashboard</title>
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
</head>
<body>

	<div class="content-w3ls" style="background: grey;">
	<div class="content-agile1">
		
	</div>
	<div class="content-agile2" style="background: grey;">

 
			<div class="form-control w3layouts" style="margin-top: 20%;"> 
				<h3 style="font-style: italic;">Welcome home, {{ username }}</h3>
			</div>


			<div class="form-control agileinfo" style="margin-top: 20%; margin-bottom: 50px;">	
				
				<ul style="padding-left: 15px; padding-bottom: 15px;">
			<li style="padding-bottom: 20px;">
				<button style="font-size: 18px;">Add New Post </button>
			</li>
			<li>
				<button style="font-size: 18px;">View all Posts </button>
	</ul>
		</div>	
		<div class="form-control agileinfo" style="margin-top: 20%; color: white; padding-left: 12px;"> 
				<a href="{% url 'theplug:logout' %}">
					<h3 style="font-style: italic;">logout</h3>
				</a>
			</div>
	
			
			
	</div>
	<div class="clear"></div>
</div>



</body>
</html>

theplug/templates/theplug/login.html
{% load static %}
<!doctype html>
<html>
<head>
<title>Login Page</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Official Signup Form Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- fonts -->
<link href="//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
<!-- /fonts -->
<!-- css --> 
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
<!-- /css -->
</head>
<body>
<h1 class="w3ls">Login Form</h1>
<div class="content-w3ls">
	<div class="content-agile1">
		
	</div>
	<div class="content-agile2">
		<form action="{% url 'theplug:login' %}" method="post">
			{% csrf_token %}

			<div class="form-control w3layouts"> 
				<input type="text" id="firstname" name="username" placeholder="Username" title="Please enter your Username" required="">
			</div>


			<div class="form-control agileinfo">	
				<input type="password" class="lock" name="password" placeholder="Password" id="password1" required="">
			</div>	
	
			
			<input type="submit" class="register" value="Login">
		</form>
		
	</div>
	<div class="clear"></div>
</div>
<p class="copyright w3l">© 2017 Official Signup Form. All Rights Reserved | TheJimoh </a></p>
</body>
</html>

theplug/templates/theplug/post_detail.html
{% load static %}
<!doctype html>
<html>
<head>
<title>Official Signup Form Flat Responsive widget Template :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Official Signup Form Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- fonts -->
<link href="//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
<!-- /fonts -->
<!-- css -->
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
<!-- /css -->
</head>
<body style="background:white;">
<h1 class="w3ls" style="color:black;">My Blog Post</h1>
<div class="content-w3ls" style="background:white;">
	<div class="content-agile2" style="color: white;">
		<span style="float:right; font-style:bold; font-size: 14px; color:black;"> <a href="{% url 'theplug:sign_up' %}">Go Home </a></span>

		<br><br><br>
	</div>
	<div class="content-agile1" style="background:none; padding-top: 50px; padding-left: 20px;">
		
			<span  style="padding-left:50px; padding-top: 50px; font-size: 12px; font-style: italic; "> {{ post.date_added }}</span>
			<h2 style="padding-left:50px; padding-top: 0px; color: black; font-family: verdana; font-size:34px; font-style: bold; font-weight: 700"> {{ post.title.upper }}</h2>
			<br>
			<span style="padding-left:50px; padding-top: 50px; padding-bottom:100px;">
				{{ post.body }}
			</span>
			<br><br>
			
		
		
	</div>

	<div class="clear"></div>
</div>
<p class="copyright w3l">© 2017 Official Signup Form. All Rights Reserved | Design by <a href="https://w3layouts.com/" target="_blank">W3layouts</a></p>
</body>
</html>

theplug/templates/theplug/posts.html
{% load static %}

<!DOCTYPE html>


<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Dashboard</title>
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
</head>
<body>

	<div class="content-w3ls" style="background: grey;">
	<div class="content-agile1">
		
	</div>
	<div class="content-agile2" style="color: white;">
		<br><br>
		<h5 style="padding-left: 20px;">Lists of recently Published Posts</h5>
		<br>
		<ul style="padding-left: 20px; list-style: bullet;">
			{% for post in posts %}
			<li> {{ post.title }}</li>
			{% endfor %}
		</ul>
	</div>
<br><br><br>
	<div class="form-control agileinfo" style="margin-top: 20%; padding-left: 20px; margin-bottom: 50px;">	
				
				<ul style="padding-left: 15px; padding-bottom: 15px;">
			<li style="padding-bottom: 20px;">
				<button style="font-size: 18px;" onclick="location.href='{% url 'theplug:create_post' %}'">Add Another Post </button>
			</li>
			
	</ul>
		</div>	
	<!-- <div class="content-agile2" style="background: grey;">

 
			<div class="form-control w3layouts" style="margin-top: 20%;"> 
				<h3 style="font-style: italic;">Create new Post</h3>
			</div>


			<div class="form-control agileinfo" style="margin-top: 20%; margin-bottom: 50px;">	
				
				<ul style="padding-left: 15px; padding-bottom: 15px;">
			<li style="padding-bottom: 20px;">
				<button style="font-size: 18px;">Add New Post </button>
			</li>
			<li>
				<button style="font-size: 18px;">View all Posts </button>
	</ul>
		</div>	
		<div class="form-control agileinfo" style="margin-top: 20%; color: white; padding-left: 12px;"> 
				<a href="{% url 'theplug:logout' %}">
					<h3 style="font-style: italic;">logout</h3>
				</a>
			</div>
	
			
			
	</div> -->
	<div class="clear"></div>
</div>



</body>
</html>

theplug/templates/theplug/sign_up.html
{% load static %}
<!doctype html>
<html>
<head>
<title>Official Signup Form Flat Responsive widget Template :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Official Signup Form Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- fonts -->
<link href="//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
<!-- /fonts -->
<!-- css -->
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
<!-- /css -->
</head>
<body style="background:white;">
<h1 class="w3ls" style="color:black;">My Blog Post</h1>
<div class="content-w3ls" style="background:white;" style="min-height: 1000px !important;">
	<div class="content-agile1" style="background:white; padding-top: 50px; padding-left: 20px;">
		{% for post in post_list %}
			<a href="{% url 'theplug:post_detail' post.id %}">
			<span  style="padding-left:50px; padding-top: 50px; font-size: 12px; font-style: italic; "> {{ post.date_added }}</span>
			<h2 style="padding-left:50px; padding-top: 0px; color: black; font-family: verdana; font-size:34px; font-style: bold; font-weight: 700">  {{ post.title.upper }}</h2>
			<br>
			{% if post.image %}
			<img src="{{ post.image.url }}" style="padding-left:50px; padding-top: 50px;">
			<br>
			{% endif %}
			<p style="padding-left:50px; padding-top: 50px; padding-bottom:100px;">
				{{ post.body|slice:":250" }}
			</p>
			</a>
			
			{% endfor %}
		
		
		
	</div>
	<div class="content-agile2" style="color: white;">
		
	</div>
	<div class="clear"></div>
</div>
<p ></p>
</body>
</html>